wget http://raw.githubusercontent.com/datacharmer/test_db/master/README.md
wget http://raw.githubusercontent.com/datacharmer/test_db/master/employees.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/employees_partitioned.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/employees_partitioned_5.1.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/images/employees.gif
wget http://raw.githubusercontent.com/datacharmer/test_db/master/images/employees.jpg
wget http://raw.githubusercontent.com/datacharmer/test_db/master/images/employees.png
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_departments.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_dept_emp.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_dept_manager.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_employees.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_salaries1.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_salaries2.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_salaries3.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/load_titles.dump
wget http://raw.githubusercontent.com/datacharmer/test_db/master/objects.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/sakila/README.md
wget http://raw.githubusercontent.com/datacharmer/test_db/master/sakila/sakila-mv-data.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/sakila/sakila-mv-schema.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/show_elapsed.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/sql_test.sh
wget http://raw.githubusercontent.com/datacharmer/test_db/master/test_employees_md5.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/test_employees_sha.sql
wget http://raw.githubusercontent.com/datacharmer/test_db/master/test_versions.sh
